C=gcc
OP=-Wall -Wextra
L=-lpthread
N=-lncurses

#il me manque à faire le all
all: serveur client 
 
serveur : GuitarGhetto.h serveur.c
	$(C) $(OP) GuitarGhetto.h serveur.c $(L) -o serveur

client : GuitarGhetto.h client.c
	$(C) $(OP) GuitarGhetto.h client.c -o client $(L) $(N)

clean :
	rm *.o
	rm serveur
	rm client