C=gcc
OP=-Wall -Wextra
L=-lpthread
N=-lncurses

#il me manque à faire le all

serveur : GuitarGhetto.h serveur.c
	$(C) $(OP) GuitarGhetto.h serveur.c $(L) -o serveur

client : GuitarGhetto.h client.c $(L) $(N)
	$(C) $(OP) GuitarGhetto.h client.c $(L) $(N) -o client

clean :
	rm *.o
	rm serveur
	rm client